import { Types } from "mongoose";

export const MOCK_EVENTS = [
  {
    _id: new Types.ObjectId().toString(),
    title: "Delhi Tech Summit 2025",
    slug: "delhi-tech-summit-2025",
    description: "The biggest gathering of tech enthusiasts, innovators, and leaders in the heart of the capital. Explore the future of AI, Web3, and beyond.",
    shortDescription: "Delhi's premier technology and innovation conference.",
    category: "Tech",
    city: "Delhi",
    venue: "Bharat Mandapam",
    address: "Pragati Maidan, New Delhi",
    date: new Date(Date.now() + 86400000 * 7), // 7 days later
    time: "10:00 AM",
    price: { amount: 500, currency: "INR", type: "Paid" },
    images: ["https://images.unsplash.com/photo-1540575861501-7ce0e2204919?q=80&w=2070&auto=format&fit=crop"],
    tags: ["tech", "ai", "innovation"],
    featured: true,
    bookmarkCount: 1250,
    viewCount: 5400,
    status: "upcoming"
  },
  {
    _id: new Types.ObjectId().toString(),
    title: "Noida Startup Pitch Fest",
    slug: "noida-startup-pitch-fest",
    description: "Launch your startup to the next level. Pitch to top VCs and angel investors in the growing NCR startup ecosystem.",
    shortDescription: "Pitch your ideas to the giants of the industry.",
    category: "Startup",
    city: "Noida",
    venue: "Sector 62 IT Hub",
    address: "B-Block, Sector 62, Noida",
    date: new Date(Date.now() + 86400000 * 14), // 14 days later
    time: "11:00 AM",
    price: { amount: 0, currency: "INR", type: "Free" },
    images: ["https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=2070&auto=format&fit=crop"],
    tags: ["startup", "funding", "networking"],
    featured: true,
    bookmarkCount: 850,
    viewCount: 3200,
    status: "upcoming"
  },
  {
    _id: new Types.ObjectId().toString(),
    title: "Classic Sufi Night @ Lodhi",
    slug: "sufi-night-lodhi",
    description: "An evening of soulful Sufi music under the stars in the historic Lodhi Garden area. Experience the spiritual magic of Delhi.",
    shortDescription: "A soulful evening of Sufi melodies.",
    category: "Cultural",
    city: "Delhi",
    venue: "The Lodhi",
    address: "Lodhi Road, New Delhi",
    date: new Date(Date.now() + 86400000 * 3), // 3 days later
    time: "7:00 PM",
    price: { amount: 1200, currency: "INR", type: "Paid" },
    images: ["https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2070&auto=format&fit=crop"],
    tags: ["music", "sufi", "culture"],
    featured: false,
    bookmarkCount: 450,
    viewCount: 1800,
    status: "upcoming"
  },
  {
    _id: new Types.ObjectId().toString(),
    title: "Indie Rock Bangalore x Delhi",
    slug: "indie-rock-bangalore-delhi",
    description: "Bangalore's top indie bands are coming to Delhi for a one-night-only showcase of the best alternative music in India.",
    shortDescription: "Alternative rock night with a coastal vibe.",
    category: "Entertainment",
    city: "Delhi",
    venue: "Hard Rock Cafe",
    address: "Janpath, New Delhi",
    date: new Date(Date.now() + 86400000 * 5),
    time: "8:30 PM",
    price: { amount: 800, currency: "INR", type: "Paid" },
    images: ["https://images.unsplash.com/photo-1501612780327-45045538702b?q=80&w=2070&auto=format&fit=crop"],
    tags: ["rock", "music", "live"],
    featured: false,
    bookmarkCount: 320,
    viewCount: 1200,
    status: "upcoming"
  },
  {
    _id: new Types.ObjectId().toString(),
    title: "Noida Marathon 2025",
    slug: "noida-marathon-2025",
    description: "Run through the clean, green boulevards of Noida. Join thousands of runners for the 5th edition of the Noida City Marathon.",
    shortDescription: "The biggest running event in Noida.",
    category: "Sports",
    city: "Noida",
    venue: "Noida City Center Stadium",
    address: "Sector 21-A, Noida",
    date: new Date(Date.now() + 86400000 * 30),
    time: "5:30 AM",
    price: { amount: 300, currency: "INR", type: "Paid" },
    images: ["https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=2070&auto=format&fit=crop"],
    tags: ["sports", "marathon", "fitness"],
    featured: false,
    bookmarkCount: 2100,
    viewCount: 8900,
    status: "upcoming"
  },
  {
    _id: new Types.ObjectId().toString(),
    title: "NCR Designers Market",
    slug: "ncr-designers-market",
    description: "Discover curated lifestyle brands, home decor, and fashion from local artisans across Delhi-NCR.",
    shortDescription: "A boutique shopping experience for curated design.",
    category: "Cultural",
    city: "Noida",
    venue: "DLF Mall of India",
    address: "Sector 18, Noida",
    date: new Date(Date.now() + 86400000 * 10),
    time: "11:00 AM",
    price: { amount: 0, currency: "INR", type: "Free" },
    images: ["https://images.unsplash.com/photo-1544928147-7972fc3359d9?q=80&w=2070&auto=format&fit=crop"],
    tags: ["design", "shopping", "art"],
    featured: false,
    bookmarkCount: 620,
    viewCount: 4500,
    status: "upcoming"
  }
];
