export interface Event {
  _id: string;
  title: string;
  description: string;
  category: string;
  city: "Delhi" | "Noida";
  date: string;
  endDate?: string;
  time: string;
  venue: string;
  address: string;
  price: {
    amount: number;
    currency: string;
    type: "Free" | "Paid" | "RSVP";
  };
  registrationUrl: string;
  images: string[];
  tags: string[];
  organizer: {
    name: string;
    email?: string;
    website?: string;
    logo?: string;
  };
  capacity?: number;
  attendees?: number;
  source: string;
  sourceUrl: string;
  featured: boolean;
  verified: boolean;
  viewCount: number;
  bookmarkCount: number;
  rating?: number;
  location?: {
    type: "Point";
    coordinates: [number, number];
  };
}

export const CATEGORIES = [
  "Tech",
  "Cultural",
  "Business",
  "Sports",
  "Education",
  "Entertainment",
  "Startup",
  "Hackathon",
  "Meetup",
  "Conference",
];

export const CITIES = ["Delhi", "Noida"];

const placeholderImages = [
  "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
  "https://images.unsplash.com/photo-1559223607-b4d0555ae227?w=800&q=80",
  "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&q=80",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
  "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&q=80",
  "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80",
  "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80",
  "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?w=800&q=80",
  "https://images.unsplash.com/photo-1548194771-ba3b0e883340?w=800&q=80",
  "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&q=80",
];

export const mockEvents: Event[] = [
  {
    _id: "1",
    title: "Delhi Tech Summit 2025",
    description: "India's largest tech conference bringing together 5000+ developers, CTOs, and tech enthusiasts. Featuring keynotes from Google, Microsoft, and leading Indian startups. Sessions covering AI/ML, Web3, Cloud Architecture, and more.",
    category: "Tech",
    city: "Delhi",
    date: "2025-05-15",
    endDate: "2025-05-17",
    time: "09:00 AM",
    venue: "Pragati Maidan, Hall 12",
    address: "Pragati Maidan, New Delhi - 110001",
    price: { amount: 2999, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/delhi-tech-summit",
    images: [placeholderImages[0], placeholderImages[1]],
    tags: ["AI", "ML", "Cloud", "Web3", "Tech"],
    organizer: { name: "TechIndia Foundation", email: "info@techindia.org", website: "https://techindia.org" },
    capacity: 5000,
    attendees: 3200,
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/e/delhi-tech-summit",
    featured: true,
    verified: true,
    viewCount: 12400,
    bookmarkCount: 842,
    rating: 4.8,
    location: { type: "Point", coordinates: [77.2435, 28.6189] },
  },
  {
    _id: "2",
    title: "Noida Startup Pitch Night",
    description: "The most exciting startup pitch competition in NCR. 20 curated startups pitching to 30+ VCs and angel investors. Network with founders, investors, and the ecosystem. Prize pool of ₹10 Lakhs.",
    category: "Startup",
    city: "Noida",
    date: "2025-05-20",
    time: "06:00 PM",
    venue: "91springboard, Noida",
    address: "A-8, Sector 68, Noida - 201301",
    price: { amount: 0, currency: "INR", type: "Free" },
    registrationUrl: "https://example.com/register/startup-pitch",
    images: [placeholderImages[1], placeholderImages[2]],
    tags: ["Startup", "VC", "Investors", "Pitch", "Funding"],
    organizer: { name: "NCR StartupHub", email: "hello@ncrstartup.in" },
    capacity: 300,
    attendees: 280,
    source: "meetup",
    sourceUrl: "https://meetup.com/noida-startups",
    featured: true,
    verified: true,
    viewCount: 8900,
    bookmarkCount: 623,
    rating: 4.6,
    location: { type: "Point", coordinates: [77.3910, 28.5900] },
  },
  {
    _id: "3",
    title: "ReactJS Delhi Meetup — Advanced Patterns",
    description: "Monthly developer meetup covering advanced React patterns, Server Components deep dive, Next.js 14 features, and performance optimization techniques. Live coding sessions and Q&A.",
    category: "Meetup",
    city: "Delhi",
    date: "2025-05-10",
    time: "11:00 AM",
    venue: "Google Startup Hub, Gurugram",
    address: "DLF Cyber City, Gurugram - 122002",
    price: { amount: 0, currency: "INR", type: "Free" },
    registrationUrl: "https://example.com/register/react-meetup",
    images: [placeholderImages[2]],
    tags: ["React", "JavaScript", "Frontend", "NextJS"],
    organizer: { name: "ReactJS Delhi Community", website: "https://reactdelhi.dev" },
    capacity: 200,
    attendees: 178,
    source: "meetup",
    sourceUrl: "https://meetup.com/reactjs-delhi",
    featured: false,
    verified: true,
    viewCount: 4200,
    bookmarkCount: 312,
    rating: 4.7,
    location: { type: "Point", coordinates: [77.0895, 28.4949] },
  },
  {
    _id: "4",
    title: "Dilli Haat Cultural Festival",
    description: "A celebration of India's rich cultural heritage featuring live classical performances, handloom exhibitions, regional food stalls from 28 states, folk dance shows, and artisan markets.",
    category: "Cultural",
    city: "Delhi",
    date: "2025-05-25",
    endDate: "2025-05-28",
    time: "10:00 AM",
    venue: "Dilli Haat, INA",
    address: "Aurobindo Marg, INA Colony, New Delhi - 110023",
    price: { amount: 100, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/dilli-haat",
    images: [placeholderImages[3], placeholderImages[4]],
    tags: ["Culture", "Food", "Art", "Music", "Dance"],
    organizer: { name: "Delhi Tourism", website: "https://delhitourism.gov.in" },
    capacity: 10000,
    attendees: 6500,
    source: "meraevents",
    sourceUrl: "https://meraevents.com/dilli-haat",
    featured: true,
    verified: true,
    viewCount: 22000,
    bookmarkCount: 1840,
    rating: 4.9,
    location: { type: "Point", coordinates: [77.2090, 28.5679] },
  },
  {
    _id: "5",
    title: "HackOn Delhi — 48hr Hackathon",
    description: "Build innovative solutions for real-world problems in 48 hours. Tracks: HealthTech, EdTech, FinTech, ClimaTech. Mentorship from industry experts, 1000+ participants expected.",
    category: "Hackathon",
    city: "Delhi",
    date: "2025-06-01",
    endDate: "2025-06-02",
    time: "09:00 AM",
    venue: "IIT Delhi Campus",
    address: "IIT Delhi, Hauz Khas, New Delhi - 110016",
    price: { amount: 0, currency: "INR", type: "Free" },
    registrationUrl: "https://unstop.com/hackons-delhi",
    images: [placeholderImages[4], placeholderImages[5]],
    tags: ["Hackathon", "Coding", "Innovation", "IIT", "Tech"],
    organizer: { name: "IIT Delhi E-Cell", email: "ecell@iitd.ac.in" },
    capacity: 1000,
    attendees: 850,
    source: "unstop",
    sourceUrl: "https://unstop.com/hack-delhi",
    featured: true,
    verified: true,
    viewCount: 18500,
    bookmarkCount: 1420,
    rating: 4.8,
    location: { type: "Point", coordinates: [77.1925, 28.5450] },
  },
  {
    _id: "6",
    title: "Noida Business Conclave 2025",
    description: "Premier B2B networking event connecting 500+ business leaders, entrepreneurs, and decision-makers. Panel discussions on future of Indian economy, global trade, and digital transformation.",
    category: "Business",
    city: "Noida",
    date: "2025-05-18",
    time: "10:00 AM",
    venue: "The Leela Ambience, Gurugram",
    address: "National Highway 48, Gurugram - 122009",
    price: { amount: 4999, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/noida-biz",
    images: [placeholderImages[5], placeholderImages[6]],
    tags: ["Business", "Networking", "Leadership", "Economy"],
    organizer: { name: "ASSOCHAM Delhi Chapter", website: "https://assocham.org" },
    capacity: 500,
    attendees: 420,
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/e/noida-biz-conclave",
    featured: false,
    verified: true,
    viewCount: 7800,
    bookmarkCount: 540,
    rating: 4.5,
    location: { type: "Point", coordinates: [77.0493, 28.5030] },
  },
  {
    _id: "7",
    title: "Cloud & DevOps Conference Delhi",
    description: "Deep dive into cloud-native architectures, Kubernetes, CI/CD pipelines, and platform engineering. Speakers from AWS, Azure, GCP, and top DevOps consultancies sharing real-world case studies.",
    category: "Conference",
    city: "Delhi",
    date: "2025-06-07",
    time: "09:30 AM",
    venue: "The Ashok Hotel",
    address: "50-B, Diplomatic Enclave, New Delhi - 110021",
    price: { amount: 1999, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/cloudconf",
    images: [placeholderImages[6]],
    tags: ["Cloud", "DevOps", "Kubernetes", "AWS", "Azure"],
    organizer: { name: "CloudNative India", website: "https://cloudnativeindia.com" },
    capacity: 800,
    attendees: 650,
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/e/cloud-devops-delhi",
    featured: false,
    verified: true,
    viewCount: 6200,
    bookmarkCount: 480,
    rating: 4.6,
    location: { type: "Point", coordinates: [77.1836, 28.5966] },
  },
  {
    _id: "8",
    title: "IPL Watch Party — Delhi Capitals",
    description: "Watch the big Delhi Capitals match LIVE on giant screens with 500+ fellow fans. Food, drinks, merchandise, and unbeatable match-day atmosphere. Don't miss cricket's biggest party!",
    category: "Sports",
    city: "Delhi",
    date: "2025-05-22",
    time: "07:00 PM",
    venue: "Connaught Place Sky Bar",
    address: "Block A, Connaught Place, New Delhi - 110001",
    price: { amount: 500, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/ipl-party",
    images: [placeholderImages[7]],
    tags: ["Cricket", "IPL", "Sports", "Delhi Capitals"],
    organizer: { name: "FanFest India" },
    capacity: 500,
    attendees: 490,
    source: "meraevents",
    sourceUrl: "https://meraevents.com/ipl-watch",
    featured: false,
    verified: true,
    viewCount: 11200,
    bookmarkCount: 920,
    rating: 4.4,
    location: { type: "Point", coordinates: [77.2167, 28.6315] },
  },
  {
    _id: "9",
    title: "AI & Machine Learning Workshop — Noida",
    description: "Hands-on 2-day intensive workshop on ML fundamentals to advanced deep learning. Projects include NLP, Computer Vision, and building production ML systems. Certificate of completion provided.",
    category: "Education",
    city: "Noida",
    date: "2025-06-14",
    endDate: "2025-06-15",
    time: "10:00 AM",
    venue: "Skill India Lab, Sector 62",
    address: "Sector 62, Noida - 201309",
    price: { amount: 3499, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/ml-workshop",
    images: [placeholderImages[8]],
    tags: ["AI", "ML", "Deep Learning", "Python", "Education"],
    organizer: { name: "DataSpark Academy", email: "learn@dataspark.in" },
    capacity: 60,
    attendees: 52,
    source: "unstop",
    sourceUrl: "https://unstop.com/ml-workshop-noida",
    featured: false,
    verified: true,
    viewCount: 3800,
    bookmarkCount: 290,
    rating: 4.7,
    location: { type: "Point", coordinates: [77.3630, 28.6100] },
  },
  {
    _id: "10",
    title: "Indie Music Night — Delhi Underground",
    description: "An intimate evening showcasing Delhi's indie music Scene. 6 independent bands performing original compositions. Genres: Indie Rock, Folk Fusion, Electronic, Jazz. Limited seats!",
    category: "Entertainment",
    city: "Delhi",
    date: "2025-05-30",
    time: "07:30 PM",
    venue: "Auro Kitchen & Bar",
    address: "Hauz Khas Village, New Delhi - 110016",
    price: { amount: 800, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/indie-night",
    images: [placeholderImages[9]],
    tags: ["Music", "Indie", "Live Music", "Entertainment"],
    organizer: { name: "Delhi Music Collective" },
    capacity: 150,
    attendees: 138,
    source: "facebook",
    sourceUrl: "https://facebook.com/events/indie-delhi",
    featured: false,
    verified: true,
    viewCount: 5600,
    bookmarkCount: 445,
    rating: 4.9,
    location: { type: "Point", coordinates: [77.1923, 28.5530] },
  },
  {
    _id: "11",
    title: "Noida Marathon 2025",
    description: "Annual full marathon and half marathon event through the scenic routes of Noida and Greater Noida. Categories for all fitness levels. Finisher medals, timing chips, and health packages included.",
    category: "Sports",
    city: "Noida",
    date: "2025-06-08",
    time: "05:30 AM",
    venue: "Noida Stadium, Sector 21",
    address: "Sector 21, Noida - 201301",
    price: { amount: 1200, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/register/marathon",
    images: [placeholderImages[0]],
    tags: ["Marathon", "Running", "Fitness", "Sports"],
    organizer: { name: "Noida Sports Authority" },
    capacity: 5000,
    attendees: 3800,
    source: "meraevents",
    sourceUrl: "https://meraevents.com/noida-marathon",
    featured: false,
    verified: true,
    viewCount: 9200,
    bookmarkCount: 680,
    rating: 4.6,
    location: { type: "Point", coordinates: [77.3539, 28.5706] },
  },
  {
    _id: "12",
    title: "Product Management Summit Delhi",
    description: "India's premier PM conference featuring talks from Product Leaders at Flipkart, Razorpay, Zepto, and global companies like Google and Meta. Workshops on product strategy, roadmapping, and data-driven decisions.",
    category: "Conference",
    city: "Delhi",
    date: "2025-06-20",
    time: "09:00 AM",
    venue: "Hyatt Regency, New Delhi",
    address: "Bhikaiji Cama Place, New Delhi - 110066",
    price: { amount: 5999, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/pm-summit",
    images: [placeholderImages[1]],
    tags: ["Product", "PM", "Strategy", "Leadership"],
    organizer: { name: "ProductByte India" },
    capacity: 600,
    attendees: 520,
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/pm-summit-delhi",
    featured: true,
    verified: true,
    viewCount: 14200,
    bookmarkCount: 1120,
    rating: 4.7,
    location: { type: "Point", coordinates: [77.1734, 28.5760] },
  },
  {
    _id: "13",
    title: "Blockchain & Web3 Meetup — Noida",
    description: "Monthly gathering of blockchain enthusiasts and builders. Topics: DeFi protocols, NFT utility in India, Solana vs Ethereum, and building on-chain applications. Open networking session post talks.",
    category: "Meetup",
    city: "Noida",
    date: "2025-05-24",
    time: "05:00 PM",
    venue: "WeWork Noida",
    address: "A-52, Sector 136, Noida - 201305",
    price: { amount: 0, currency: "INR", type: "Free" },
    registrationUrl: "https://example.com/web3-noida",
    images: [placeholderImages[2]],
    tags: ["Web3", "Blockchain", "DeFi", "NFT", "Crypto"],
    organizer: { name: "Web3 NCR Community" },
    capacity: 100,
    attendees: 86,
    source: "meetup",
    sourceUrl: "https://meetup.com/web3-noida",
    featured: false,
    verified: true,
    viewCount: 3100,
    bookmarkCount: 240,
    rating: 4.3,
    location: { type: "Point", coordinates: [77.3400, 28.5200] },
  },
  {
    _id: "14",
    title: "Delhi Comedy Festival",
    description: "3-day stand-up comedy extravaganza featuring 20+ comedians including AIB, Biswa Kalyan Rath, and rising stars. English and Hindi sets, bar and grill. Perfect weekend plan!",
    category: "Entertainment",
    city: "Delhi",
    date: "2025-07-04",
    endDate: "2025-07-06",
    time: "07:00 PM",
    venue: "Epicentre Amphitheatre, Gurugram",
    address: "Sector 44, Gurugram - 122003",
    price: { amount: 1500, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/comedy-festival",
    images: [placeholderImages[3]],
    tags: ["Comedy", "Stand-up", "Festival", "Entertainment"],
    organizer: { name: "LOL Productions" },
    capacity: 2000,
    attendees: 1800,
    source: "facebook",
    sourceUrl: "https://facebook.com/events/delhi-comedy",
    featured: true,
    verified: true,
    viewCount: 20000,
    bookmarkCount: 1750,
    rating: 4.8,
    location: { type: "Point", coordinates: [77.0569, 28.4459] },
  },
  {
    _id: "15",
    title: "EdTech Founders Summit — Noida",
    description: "Bringing together 100+ EdTech founders to discuss the future of learning in India. Special tracks on K12, higher education, skill development, and edtech fundraising in 2025.",
    category: "Startup",
    city: "Noida",
    date: "2025-06-12",
    time: "10:00 AM",
    venue: "Amity University Auditorium",
    address: "Amity University Campus, Sector 125, Noida - 201313",
    price: { amount: 1499, currency: "INR", type: "Paid" },
    registrationUrl: "https://example.com/edtech-summit",
    images: [placeholderImages[4]],
    tags: ["EdTech", "Education", "Startup", "Founders"],
    organizer: { name: "EdTech India Alliance" },
    capacity: 300,
    attendees: 210,
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/edtech-noida",
    featured: false,
    verified: true,
    viewCount: 5400,
    bookmarkCount: 390,
    rating: 4.5,
    location: { type: "Point", coordinates: [77.3350, 28.5450] },
  },
];

export function getEventById(id: string): Event | undefined {
  return mockEvents.find((e) => e._id === id);
}

export function getEventsByCity(city: string): Event[] {
  return mockEvents.filter((e) => e.city === city);
}

export function getEventsByCategory(category: string): Event[] {
  return mockEvents.filter((e) => e.category === category);
}

export function getFeaturedEvents(): Event[] {
  return mockEvents.filter((e) => e.featured);
}

export function searchEvents(query: string): Event[] {
  const q = query.toLowerCase();
  return mockEvents.filter(
    (e) =>
      e.title.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.tags.some((t) => t.toLowerCase().includes(q)) ||
      e.category.toLowerCase().includes(q) ||
      e.venue.toLowerCase().includes(q)
  );
}

export function getStats() {
  return {
    totalEvents: mockEvents.length,
    delhiEvents: getEventsByCity("Delhi").length,
    noidaEvents: getEventsByCity("Noida").length,
    freeEvents: mockEvents.filter((e) => e.price.type === "Free").length,
    categories: CATEGORIES.length,
    sources: 10,
    totalBookmarks: mockEvents.reduce((a, e) => a + e.bookmarkCount, 0),
    totalViews: mockEvents.reduce((a, e) => a + e.viewCount, 0),
  };
}
